# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
require 'faker'

#Artiste.destroy_all

Artiste.create!([{
  name: "Guillaume Bellom",
  color: Faker::Color.hex_color,

},
{
  name: "Mathilde Calderini",
  color: Faker::Color.hex_color,
},
{
  name: "Edgar Moreau",
  color: Faker::Color.hex_color,
},
{
  name: "Yan Levionnois",
  color: Faker::Color.hex_color,
},
{
  name: "Renaud Capuçon",
  color: Faker::Color.hex_color,
},
{
  name: "Nicholas Angelich",
  color: Faker::Color.hex_color,
},
{
  name: "Khatia Buniatishvili",
  color: Faker::Color.hex_color,
},
{
  name: "Martha Argerich",
  color: Faker::Color.hex_color,
},
{
  name: "Dong Hyek Lim",
  color: Faker::Color.hex_color,
},
{
  name: "David Kadouch",
  color: Faker::Color.hex_color,
}

])

p "Created #{Artiste.count} artistes"

#Engagement.destroy_all
20.times do
mynumber = Faker::Number.between(from: 1, to: 10)
begindate = Faker::Date.between(from: 5.month.ago, to: 1.year.from_now)
enddate = begindate + mynumber.days
Engagement.create!(
    title: Faker::Address.city,
    startengagement: begindate,
    endengagement:  enddate,
    artiste_id: Artiste.order(Arel.sql('RANDOM()')).first.id,
    status: "confirmed" 

)
end

20.times do
mynumber = Faker::Number.between(from: 1, to: 10)
begindate = Faker::Date.between(from: 5.month.ago, to: 1.year.from_now)
enddate = begindate + mynumber.days  
Engagement.create!(
    title: Faker::Address.city,
    startengagement: begindate,
    endengagement:  enddate,
    artiste_id: Artiste.order(Arel.sql('RANDOM()')).first.id,
    status: "invitation"  

)
end

20.times do
mynumber = Faker::Number.between(from: 1, to: 10)
begindate = Faker::Date.between(from: 5.month.ago, to: 1.year.from_now)
enddate = begindate + mynumber.days  
Engagement.create!(
    title: Faker::Address.city,
    startengagement: begindate,
    endengagement:  enddate,
    artiste_id: Artiste.order(Arel.sql('RANDOM()')).first.id,
    status: "option"  

)
end

300.times do
Contact.create!(
    name: Faker::Name.last_name,
    surname: Faker::Name.first_name 
    
  )
end

messtructures = [ 
"21st Century Concerts Luzern",
"21th Century Concerts",
"Abbatiale Saint Michel de Nantua",
"Académie Haskil",
"Académie Internationale d'Eté de Nice",
"Académie Maurice Ravel - Saint Jean de Luz",
"Académie Philippe Jaroussky",
"Academy of St. Martin in the Fields",
"Accademia Nazionale di Santa Cecilia",
"Accademia Perosi Onlus",
"Accentus / Insula Orchestra",
"A D A M A",
"Adler",
"Adler",
"Affidia - Croisières du Ponant - Le Lyrial",
"Agence Artistique Jacques Thelen",
"Agence Artistique Paul Massendari",
"Agence de Concerts Caecilia",
"Agence Privat Gala Geneva",
"Albertville Dôme Théâtre",
"Albertville - Service Culturel",
"Al Bustan International Festival of Music and the Performing Arts",
"ALOUICE  /  Sarl",
"Ambassade de France en Andorre",
"AMC - Artists Management Company",
"AME Association pour la Musique à Eygalières",
"American Hospital Istambul",
"Amici della Musica Firenze",
"Amsterdam Sinfonietta",
"Animation Musicale à l'Université de Rouen - AMU",
"Animato Foundation",
"Annecy Classic Festival",
"A.R.A.L. / Festival International de Musique Sacrée de Lourdes",
"Ares & Company France",
"Argerich's meeting point in Beppu",
"Aria",
"ARTE",
"Artepiano",
"Askonas Holt",
"Aspen Music Festival",
"Association Ars Mobilis",
"Association Avetis",
"Association Bourg arts et Vins",
"Association des Amis de l'Orgue de L'Isle-Adam",
"Association Finland Festival",
"Association Fortissimo",
"Association Les Moments Musicaux",
"Association Les Nuits du Château de la Moutte",
"ASSOCIATION  « MEGEVE FESTIVAL SAVOY TRUFFLE »",
"Association Minutes Culturelles",
"Association Olivier Messiaen au Pays de la Meije",
"Association Polyèdres",
"Association Pornic Classic",
"Association Voix Réunies",
"Assoziation Franz Schubert Barcelona",
"Athens State Orchestra",
"Auditori Girona",
"Auditorio Nacional de la Musica - Madrid",
"Auditorio Principe Felipe - Oviedo",
"Auditorium de Bordeaux",
"Auditorium du Musée du Louvre",
"Auditorium Manzoni Bologne",
"Auditorium & Orchestre National de Lyon",
"Aurora Orchestra",
"Azerbaidjan State Symphonic Orchestra",
"Azerbaidjan State Symphonic Orchestra",
"Bach en Combrailles",
"Bad Kissingen",
"Baldrighi",
"Baltic Musical Seasons Foundation",
"Baltimore Symphony",
"Barbican Centre",
"Basel Chamber Orchestra | Orchestre de chambre de Bâle",
"BBC Proms",
"BBC Scotland",
"Beethovenfest",
"Belgrade Philharmonic Orchestra",
"Berin Iglesias Art",
"Berliner Konzertagentur 3-Klang",
"Berlin Staatskapelle",
"Berlin Staatskapelle",
"Berlin Staatsoper",
"Bernard Magrez SAS",
"Berner Symphonieorchester / Kammermusik Bern",
"Biarritz Piano Festival",
"Bilkent Symphony Orchestra",
"Blaricum Festival Netherlands",
"Blaricum Festival Netherlands",
"Blaricum Festival Netherlands",
"Blue Head",
"Bochumer Symphoniker",
"Boston Symphony Orchestra",
"Bravo! Vail Music Festival",
"Brno Philharmonic",
"Brno Philharmonic",
"Brussels Philharmonic",
"Bucharest Grand Palace Hall",
"Bucharest Grand Palace Hall",
"Budapest Festival Orchestra",
"Buenos Aires Philharmonic",
"Burgdorfer Schloßkonzerte",
"Camerata Salzbourg",
"Camerata Venia",
"CAMI",
"Carl Nielsen International Violin Competition",
"Carnegie Hall",
"Casa de Musica",
"Céleste Productions - Les Grandes Voix",
"Cello Biennale Amsterdam",
"CENTRE CULTUREL DE LA SARTHE",
"Centre de Musique de Chambre de Paris",
"Centre Lyrique Clermont Auvergne",
"C'est Pas Classique",
"Chamber Orchestra of Europe",
"Chambord Festival",
"Chateau de Versailles Spectacles",
"Château Romanin",
"Chicago Symphony Orchestra",
"Chopin Piano Competition",
"Chorégies d'Orange",
"Choriner Musiksommer",
"Cité de la Musique / Philharmonie de Paris",
"Classic à Guéthary",
"Classic à Juan",
"Classique au Vert",
"Columbia Artists",
"Concertgebouw Amsterdam",
"Concertinos de Pornic",
"Concerto Budapest",
"Concerts du Printemps",
"Concours International de Piano d'Epinal",
"Concours Long-Thibaud-Crespin",
"Concours Reine Elisabeth",
"Concurso Internacional de Piano Vigo",
"Conseil Immobilier Provence",
"Conseil régional Auvergne-Rhône-Alpes",
"Crans-Montana Classics",
"Crans-Montana Classics",
"Croisière Ponant/Radio Classique",
"Croisi Europe",
"Czech Philharmonic",
"Czech Philharmonic",
"Danish National Symphony Orchestra",
"Department of Culture and Tourism Abu Dhabi",
"Detroit Symphony Orchestra",
"Deutsche Radio Philharmonie",
"Deutsche Symphonie-Orchester Berlin",
"Dimanche Musicaux de Castres",
"Dispeker Artists",
"Dortmund Konzerthaus",
"Dresdner Musikfestpiele",
"Dresdner Philharmonie - Philharmonique de Dresde",
"Dubrovnik Festival",
"Duetto Management",
"ElbPhilharmonie Hambourg",
"Electron Libre Productions",
"Engadin Festival",
"Ensemble Wien-Berlin",
"Ensemble Wien-Berlin",
"Escapades Musicales",
"Escapades musicales d'arcachon",
"Espace Malraux Chambéry",
"Essen Philharmonic Orchestra",
"Estivales de Musique en Médoc",
"Estivales de Taillades",
"European Foundation For Support of Culture (Malta)",
"European Philharmonic of Switzerland",
"Festi-Classique",
"Festival 1001 Notes",
"Festival Abbaye Lucerne",
"Festival Alexandre Paley et ses amis",
"Festival Artenetra",
"Festival autour d'un piano - Château de Carrouges",
"Festival Autour du Ventoux",
"Festival aux Chandelles",
"Festival Beaulieu",
"Festival Berlioz - La Côte Saint André",
"Festival Besançon Musique",
"Festival Cello Fan",
"Festival Chopin and his Europe",
"Festival Chopin, Paris",
"Festival Clef de Soleil - Lille",
"Festival d’Ambronay",
"Festival d'Auvers-sur-Oise",
"Festival de Barbizon",
"Festival de Briançon",
"Festival de Carcassonne",
"Festival de Chaillol",
"Festival de Chantilly / Iddo Bar-Shai",
"Festival de Deauville",
"Festival de la Chaise Dieu",
"Festival de la haute clarée",
"Festival de Laon",
"festival de la Vézère",
"Festival de l'Epau",
"Festival de Ljubljana",
"Festival de l'Orangerie de Sceaux",
"Festival de Menton",
"Festival de Musique de Chambre d'Arcachon",
"Festival de Musique de Chambre de Perros-Guirec",
"Festival de Musique de Chambre de Roland Pidoux",
"Festival de Musique de Chambre de Saint-Paul de Vence",
"Festival de Musique de Sully",
"Festival de Musique de Toulon",
"Festival de Musique de Toulon",
"Festival de Musique du Mont Saint-Michel et sa Baie",
"Festival de Nohant",
"Festival de Pâques d'Aix-en-Provence",
"Festival de Piano aux Jacobins",
"Festival de Piano en Saintonge",
"Festival de Pont-Croix",
"Festival de Rocamadour",
"Festival de Saint-Denis",
"Festival de Saint-Riquier",
"Festival de Salzburg ",
"Festival de Santa Repara",
"Festival des Arcs",
"Festival des forêts",
"Festival des Heures Musicales de Biot",
"Festival des Lumières",
"Festival des Nuits Romantiques",
"Festival de Wallonie",
"Festival de Wissembourg",
"Festival d'Eygalieres",
"Festival du Comminges",
"Festival du Forez",
"Festival du Périgord Noir",
"Festival du Périgord Pourpre - L'Été Musical en Bergerac",
"Festival du Royaumond",
"Festival du Vexin",
"Festival du Vigan",
"Festival Format Raisin",
"Festival Grands Crus Musicaux",
"Festival Ile de France",
"Festival Internacional de Música Pau Casals",
"Festival International de Colmar",
"Festival International de Musique de Chambre de Salon de Provence",
"Festival International de musique d'Espinho",
"Festival International de Piano de la Roque d'Anthéron",
"Festival International de Quatuors à Cordes du Luberon",
"Festival International des Arts de Bordeaux Métropole",
"Festival Itinéraires en Morbihan",
"Festival Jeunes Talents à Loudun",
"Festival La Dame Des Aulnes",
"Festival ""la semaine musicale",
"Festival Les Athénéennes",
"Festival Les Chaises Musicales",
"Festival Les Musicales de Colmar",
"Festival Les Musicales de Redon",
"Festival les solistes de bagatelle",
"Festival Lind'Art Morzine",
"Festival Liszt en Provence",
"Festival Martha Argerich Hambourg",
"Festival MDR Musiksommer",
"Festival Musica Strasbourg",
"Festival Musiq3 - RTBF",
"Festival Musique en Côte Basque",
"Festival Musique Mont Saint-Michel",
"Festival Musiques au pays de Gabriel Fauré - Pamiers",
"Festival Musiques au Port",
"Festival Notre-Dame-de-Vie / Service Culturel Ville de Mougins",
"Festival Nouveaux Talents Villers-sur-Mer",
"Festival Obernai",
"Festival Owon",
"Festival Pianissimes",
"Festival Pianistico Internazionale di Brescia e Bergamo",
"Festival Piano en Valois",
"Festival Radio France Montpellier",
"Festival Romantique du Loir",
"Festival Saou Chante Mozart",
"Festival Septembre Musical",
"Festival Sully Classique",
"Festival Tempo Piano Classique Le Croisic",
"Festival Tons Voisins - Albi",
"Festival Tout'Ouïe",
"Festival Transsibérien",
"Festival un Violon sur le Sable",
"Festival Vent sur l'Arbre",
"Festival Vivacello Moscou",
"Festspiele Mecklenburg Vorpommern",
"Festspiele Mecklenburg-Vorpommern",
"Fêtes musicales de Savoie",
"Fêtes Musicales en Touraine",
"Filharmonica della Scala",
"Filharmonica della Scala",
"Finnish Radio Orchestra",
"Flagey",
"Flâneries Musicales de Reims",
"Folle Journée de Tokyo",
"Fondation Cully Classique / Festival Lavaux Classique",
"Fondation Lavaux Classic",
"Fondation Lombard",
"Fondation Louis Vuitton",
"Fondation Pierre Gianadda",
"Fondation Pierre Gianadda Martigny",
"Fournier Productions - Salle Gaveau",
"France Musique",
"Frankfurter Hof Mainz",
"Frauenkirche Dresden ",
"Fundacio l'Atlantida",
"Fundacion CorpArtes Santiago",
"Fundacion del Teatro Mayor Bogota",
"Fundació Pau Casals",
"GCONNEXION",
"George Enescu Festival",
"Georgisches Kammerorchester",
"Gewandhaus Orchester Leipzig",
"Goette",
"Grafenegg Festival",
"Grand Teton Music Festival",
"Grand théâtre de Genève",
"Grand Théâtre de Genève",
"Grand Théâtre de Provence",
"Grant Park Music Festival",
"Great Mountain Festival and School",
"Greek Festival - Athen",
"Groves Artists",
"Gstaad - Yehudi Menuhin Festival",
"Gulbenkian Musica  - Fondation Gulbenkian",
"Harriman Jewell Series",
"Harrison Parrot",
"Heidelberger Frühling - Printemps d'Heidelberg",
"Helsinki Philharmonic Orchestra",
"Herkulessaal Munich",
"Heures musicales en Monedières",
"Hindsgavel Festival",
"Hof Symphoniker",
"Hollywood Bowl",
"Hong-Kong Art Festival",
"Hong Kong Philharmonic",
"Hong Kong Sinfonietta",
"Hôtel Bedford Paris",
"Iceland Symphony Orchestra",
"Il Pomo d'Oro",
"Imago Slovenia",
"Imperial Annecy Festival",
"IMPRESARIAT  SIMMENAUER Kurfürstendamm 211 • DE - 10719 Berlin",
"Institut Valencia de Cultura",
"Interclassique",
"I Pomeriggi",
"Israel Philharmonic",
"Istanbul Music Festival",
"Itinéraire Baroque en Périgord Vert",
"Ivy Artists",
"JapanArts",
"Jeanine Roze Production",
"Jerusalem International  Chamber Music Festival",
"Jeudis Musicaux de Royan",
"Jeunes Interprètes - Bienne",
"JMAD Events",
"«Journées de la musique de la maison Balabanov»",
"Journées Musicales entre Loire et Loir",
"Kajimoto",
"Kammerakademie Potsdam",
"KBS - Korean Broadcast Symphony Orchestra",
"KD Schmid",
"Kharkiv Music Fest",
"Kissinger Sommer",
"Klassik Sterne Aarau",
"Klavier Festival Ruhr",
"Kocyan",
"Kölner Philharmonie - Philharmonie de Cologne",
"Konzerthaus Berlin",
"Kremerata Baltica",
"Kultur Gesellschaft Glarus",
"KulturMusikKonzepte",
"Kulturpalast Dresden",
"Kulturreferat der Stadt Kaiserslautern",
"Kulturring Heilbronn",
"La Coursive Scène Nationale La Rochelle",
"La Faïencerie Théâtre",
"La Folle Journée d'Ekaterinebourg",
"La Folle Journée de Varsovie",
"L'Agence Artistik",
"La Grange de Meslay",
"LA  MAIRIE  D'ANGLET",
"La Mascara de Orfeo",
"La Seine Musicale",
"La semaine musicale",
"la Staatskapelle Mecklenburg",
"Latvian National Symphony Orchestra",
"LAUSANNE  SOLOISTS",
"Le coeur en musique",
"Le CREA",
"L'Ecrin Musical",
"Les 8 de Montcabrier",
"Les amis de la musique à Deauville",
"Les Amis de la Musique de Clermont-Ferrand",
"Les Amis de la Musique de Vaison la Romaine",
"Les Amis de Saint-Robert",
"Les Amis de Saint-Victor",
"Les Amis du Château de Verges - Les Castellins",
"Les Concerts de Grandson",
"LES  CONCERTS  DE  POCHE",
"Les Concerts Parisiens",
"LES DIMANCHES MUSICAUX de CASTRES       ",
"Les Estives Musicales Internationales de Louvie-Juzon",
"Les Grands Interprètes - Toulouse",
"Les Heures Musicales du Haut Anjou",
"Les Mardis Musicaux d'Angers",
"Les Moments Musicaux de Notre-Dame",
"Les Musicales d'Arradon",
"Les Musicales de l'Orangerie",
"Les Musicales de Mortagne et du Perche",
"Les Musicales de Normandie",
"Les musicales d'Issoire Val d'Allier",
"Les Musicales d'Orcival",
"Les musicales du Lubéron",
"Les Musicales du Pays des Couzes",
"Les Musicales Gabriel Fauré",
"Les Nocturnes Sainte Victoire",
"Les Nuits de la Citadelle - Sisteron",
"Les Nuits du Piano d'Erbalunga",
"Les Nuits Musicales de la Citadelle - Villefranche sur Mer",
"Les nuits musicales de la Tuilerie",
"Les nuits musicales d'Uzès",
"Les Petites Fugues d'Epinal",
"Les Petites Heures SAS",
"Les pianissimes",
"L'Esprit du Piano",
"Les samedis musicaux de Chartres",
"Les soirées du Castellet",
"Les Soirées Musicales de Venejan",
"Les Solistes à Bagatelle",
"Les Solistes de Demain",
"Les vacances de Monsieur Haydn",
"Lille Pianos Festival",
"Listahatio i Reykjavik",
"Lisztomanias Piano",
"LOFT music GmbH",
"London Philharmonic Orchestra",
"London Symphony Orchestra",
"Los Angeles Chamber Orchestra",
"Los Angeles Chamber Orchestra",
"Los Angeles Philharmonic",
"Louisiana Museum",
"Lucerne Festival",
"Ludwigsburger Schlossfestspiele ",
"Ludwig van Beethoven Easter Festival Warsaw - Festival Beethoven Varsovie",
"Lugano Musica",
"Luzerner Sinfonieorchester - Orchestre Symphonique de Lucerne",
"Luzern Piano Festivak",
"M",
"Mahler Chamber Orchestra",
"Maison des Associations",
"Malmo chamber music festival - Suède",
"Mannheimer Philharmoniker | Orchestre Philharmonique de Mannheim",
"Marseille Concerts",
"Martha Argerich Festival Hamburg",
"MC2 Grenoble",
"Mécénat Chirurgie Cardiaque",
"Mécénat Chirurgie Cardiaque",
"Miami International Piano Festival",
"Milwaukee Symphony Orchestra",
"Mirecourt - Concours Violon",
"Mito Settembre Musica",
"Mitteldeutscher Rundfunk MDR",
"Moissac Culture Vibrations",
"Moments Musicaux Allegro Amabile",
"Mozarteum Salzburg",
"Mozartfest Würzburg",
"Muenchner Symphoniker - Orchestre Symphonique de Munich",
"Münchner Philharmoniker | Munich Philharmonic",
"Musée de l'Armée - Invalides",
"Musée des Beaux-Arts de Montréal",
"Musée Würth",
"Musicades et Olivades",
"Musicales à la ferme",
"Musicales de Clairegoutte et du Rahin",
"Musicales du trophée",
"Musicales et Olivades",
"Musicales sur le Sable",
"Musica Mundi ASBL",
"Musicancy",
"Musica Vitae - Suède",
"Music Worcester",
"Musikfest Bremen",
"Musikkollegium Winterthur",
"Musikverein Vienne",
"Musique à Beauregard",
"Musique à Fontmorigny",
"Musique à la ferme",
"Musique au Château - Festival Automnales",
"Musique de Chambre à Giverny",
"Musique en Albret",
"Musique Espérance Albi",
"Musiques à Bagatelle",
"Musiques et Patrimoine en Pays Chinonais",
"Muziekgebouw ",
"Nancyphonies",
"National Cello Biennale Amsterdam",
"National Philharmonic Prague",
"National Symphony Orchestra (Washington)",
"Navarra Symphonic Orchestra - Orchestre Symphonique de Navarre",
"Neues Orchester Basel",
"New York Philharmonic",
"NFM Wroclaw Philharmonic",
"NFM Wroclaw  Philharmonic",
"Nice Classic Live",
"Norddeutscher Rundfunk",
"North Arkansas Symphony Orchestra",
"North Carolina Symphony Orchester",
"Nouveaux Talents et Invités",
"Nuits Musicales du Suquet",
"Nuits Romantiques du Lac du Bourget",
"Office de Tourisme et des Congrès d'Antibes",
"Office de Tourisme et des Congrès d'Antibes Juan Les Pins60 Chemin des Sables",
"Old & New MonteCarlo",
"Olso Philharmonic",
"ONCT - Orchestre National du Capitole de Toulouse",
"ONDIF - Orchestre National d'Ile de France",
"ONF - Orchestre National de France",
"ONL - Orchestre National de Lille",
"ONPL - Orchestre National Pays de la Loire",
"Opéra Angers-Nantes",
"Opéra de Bordeaux - Grand théâtre",
"Opéra de Dijon",
"Opéra de Lille",
"Opéra de Limoges",
"Opéra de Lyon",
"Opéra de Massy",
"Opéra de Metz",
"Opéra de Nice / Orchestre Philharmonique de Nice",
"Opéra de Paris",
"Opéra de Reims",
"Opéra de Rennes",
"Opéra de Rennes",
"Opéra de Rouen Normandie",
"Opéra de Saint-Etienne",
"Opéra de Toulon",
"Opéra de Tours",
"Opéra de Vichy",
"Opéra Grand Avignon",
"Opéra Municipal de Marseille",
"Opéra National de Hongrie",
"Opéra National de Lorraine",
"Opéra National Du Rhin",
"Opéra - Orchestre National de Montpellier Occitanie",
"Opéra royal de Wallonie (Liège)",
"Opéra Royal du Château de Versailles",
"Opéra-Théâtre de Clermont-Ferrand",
"Opera Vlaanderen (Anvers)",
"Opus 3 Artists",
"Orchestra de l'Aerna di Verona - Orchestre de l'Arène de Verone",
"Orchestra della Toscana",
"Orchestra e Coro del Teatro Petruzzelli",
"Orchestra Sinfonica Nazionale RAI",
"Orchestre Colonne",
"Orchestre d'Auvergne - Clermond Ferrand",
"Orchestre de Besançon",
"Orchestre de Cannes",
"Orchestre de chambre de Lausanne",
"Orchestre de Chambre de Paris",
"Orchestre de Chambre de Paris",
"Orchestre de Chambre de Toulouse",
"Orchestre de la radio de Leipzig MBR",
"Orchestre de la Suisse Italienne",
"Orchestre de la Suisse Romande",
"Orchestre de l'Opéra de Paris",
"Orchestre de Paris",
"Orchestre de Pau Pays de Béarn",
"Orchestre de Picardie",
"Orchestre des Champs-Elysées",
"Orchestre des Jeunes de Bahia",
"Orchestre des Pays de Savoie",
"Orchestre de Strasbourg",
"Orchestre Les Siècles",
"Orchestre Métropolitain",
"Orchestre Métropolitain de Montréal",
"Orchestre National Bordeaux Aquitaine",
"Orchestre National de Belgique",
"Orchestre National de Bretagne",
"Orchestre National de Metz",
"Orchestre Nouvelle Aquitaine",
"Orchestre Pasdeloup",
"Orchestre Philharmonique de Luxembourg ",
"Orchestre Philharmonique de Marseille / Opéra de Marseille",
"Orchestre Philharmonique de Monte Carlo",
"Orchestre Philharmonique de Radio France / Festival Présences / Auditorium de Radio France",
"Orchestre Philharmonique de Strasbourg",
"Orchestre Philharmonique Royal de Liège",
"Orchestre Régional Avignon-Provence",
"Orchestre Royal de Chambre de Wallonie",
"Orchestre Symphonique de Bilbao",
"Orchestre symphonique de Goteborg",
"Orchestre symphonique de la NHK",
"Orchestre Symphonique de l'Aube",
"Orchestre Symphonique de Montreal",
"Orchestre Symphonique de Mulhouse",
"Orchestre Théâtre National de Mannheim",
"Oria Milano",
"Orleans Concours International",
"Orquesta de Sevilla",
"Orquesta Sinfónica de Baleares",
"Orquesta Sinfónica de Galicia ",
"Orquestra Sinfònica de Barcelona i Nacional de Catalunya - Orchestre Symphonique de Barcelone",
"Oslo Philharmonic",
"Oxford Philharmonic Orchestra",
"Palau de la Musica Catalana",
"Palazzetto Bru Zane - Centre de Musique Romantique Française",
"Paléo Festival",
"Philharmonie du Luxembourg",
"Phillips Collection - Washington",
"Piano 4 Etoiles",
"Piano à Lyon",
"Piano à Porrentruy | Piano à Saint-Ursanne",
"Piano Folies - Touquet Paris Plage Tourisme",
"Piano Pic",
"Pianoscope Beauvais",
"Pittsburgh Symphony Orchestra",
"Pradet - Festival Musique à la Cour",
"Printemps des Arts de Monte Carlo",
"Printemps du Violon",
"Pro Arte Frankfurter Konzertdirektion",
"Promenades musicales du pays d'Auge",
"PROQUARTET - CEMC",
"Quincena Musical de San Sebastian",
"Quinzaine Musicale de San Sebastian",
"Radio Classique",
"RC Prod",
"Real Filharmonía de Galicia ",
"Rencontre musicales de Saint-Cézaire",
"Rencontres Artistiques de Bel-Air",
"Rencontres Classiques de Vernier",
"Rencontres Musicales de Calenzana",
"Rencontres musicales de Haute-Provence",
"Rencontres musicales de la Méditerranée ",
"Rencontres musicales de la Méditerranée ",
"Rencontres musicales de Noirlac",
"Rencontres Musicales de Noyers",
"Rencontres Musicales d'Evian",
"Resia",
"Rheingau Musik Festival",
"Riaskoff Concert Management",
"Riga Jurmala Music Festival Foundation",
"Romaniam Atheneum",
"Romanian Foundation for Excellence in Music",
"Rosendal Chamber Music Festival",
"Rsy Concert Hall Rolle",
"Rotterdam Philharmonic Orchestra",
"Royal Albert Hall - Londres",
"Royal Commissioner for Al Ula Festival",
"Royal Festival Hall",
"Royal Philharmonic Orchestra",
"Rundfunk Sinfonieorchester Berlin",
"Russian National Orchestra / Orchestre National de Russie",
"SAEM La Folle Journée",
"Salzburg Festspiel - Festival de Salzbourg",
"Samuel  PARENT",
"San Francisco Symphony",
"San Francisco Symphony",
"Scène 55 - Mougins",
"Scène Nationale de Besançon",
"Schaffhauser Meisterkonzerte",
"Schleswig-Holstein Music Festival",
"Schloss Elmau",
"Schmidt",
"Schubertiade",
"Schwarzenberg",
"Scottish Chamber Orchestra",
"Seattle Symphony Orchestra",
"Senlis en Musique",
"Septembre Musical de l'Orne",
"SEQUENZA COM'PROD",
"Sérénades en Barronies",
"Settimane Musicali Ascona",
"Shanghai Concert Hall",
"Shanghai Symphony Orchestra",
"Sinfonia en Périgord – Festival baroque",
"Sinfonieorchester St. Gallen",
"Singapore Symphonia - Orchestre Symphonique de Singapour",
"Sociedad Filarmonica de Bilbao",
"Societa dei Concerti - Bolzano",
"Societa dei Concerti - Bolzano",
"Societa dei Concerti - Milano",
"Società del Quartetto Milano",
"Société Chopin à Paris",
"Société de Musique de Chambre de Marseille",
"Société des Concerts de la Chaux de Fonds",
"Société Tropézienne des Amis de la Musique",
"Solistes Européens Luxembourg",
"Sommets Musicaux de Gstaad",
"Southbank Centre",
"South Netherland Philharmonic",
"Staatskapelle Berlin",
"Stadt Waiblingen - Fachbereich Kultur und Sport",
"Stavanger Symphony Orchestra",
"Steinway and Sons Paris",
"Sté Little TRIBECA",
"Sté VINCI",
"Stichting voor  Kammermusiek den Haag",
"St Petersburg Symphony Orchestra",
"Stuttgart LiederHalle",
"Suntory Hall ARK Classics",
"Suntory Hall Summer Festival",
"Swiss Chamber Concerts",
"SWR Symphonieorchester",
"Sydney Symphony Orchestra",
"Symphonieorchesters des Bayerischen Rundfunks",
"Symphoniker Hamburg",
"Taiwan Philharmonic",
"Tampere Filharmonia / Tampere Philharmonic Orchestra",
"Taormina Opera Stars",
"Tartini Festival",
"Tauberphilharmonie Weikersheim",
"Tchaikovsky Competition",
"Teatro Communale",
"Teatro del Centro Cultural CA660",
"Teatro Galli Rimini",
"Teatro Petruzzelli - Bari",
"Teatro Verdi",
"Test structure",
"Theater Gütersloh",
"Théâtre de Caen",
"Théâtre de Nimes",
"Théâtre des Champs-Elysées",
"Théâtre du Mariinsky",
"Théâtre La Scala Paris",
"Théâtre Magdeburg",
"Théâtre Olympia d'Arcachon",
"Théâtre Royal de la Monnaie",
"The Music Plant Co.",
"The Philadelphia Orchestra",
"The Philharmonia Orchestra",
"Thueringer Bachwochen",
"Tiroler Symphonieorchestre Innsbruck",
"Tokyo Metropolitan Symphony Orchestra",
"Tokyo Symphony Orchestra",
"Tonhalle Dusseldorf",
"Tonhalle Orchester",
"Tonkunstler Orchestra",
"Toronto Symphony Orchestra",
"Townsville Festival Australia",
"Trompette en balade",
"Trondheim Symfonieorkester",
"Tsinandali Festival",
"Turku Music Festival",
"Unione Musicale Torino",
"Utah Symphony Orchestra",
"Vancouver Symphony Orchestra",
"Variations Classiques Annecy",
"Variations Musicales de Tannay",
"Verbier Festival",
"Victoires de la Musique Classique",
"Ville dAnglet",
"Ville de Nice - Opéra Nice Côte dAzur",
"Warner Classics",
"Warner Classics",
"Warsaw Philharmonic",
"Warsaw Philharmonic Hall",
"Weilburger",
"Weingarten, Kultur und Kongresszentrum Oberschwaben",
"Weinstadt Artists Management",
"West-Eastern Divan Orchestra",
"Wiener Konzerthausgesellschaft",
"Wiener Symphoniker",
"Wigmore Hall",
"Winderstein",
"Wonderfeel Festival",
"Wright Music Management",
"Wuhan Philharmonic Orchestra",
"Wurth Philharmoniker",
"Wurttembergisches Kammerorchester",
"Xan Concert Hall",
"Zentrum Paul Klee - Centre Paul Klee",
"Zermatt  Music Festival",
"Zurich Chamber Players"
]

messtructures.each do |struc|
  Structure.create!(
    title: struc
    )
end


p "Created 60 engagements"
